layoutdir = "themes/hugo-academic-group/layouts"
publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
#baseurl = "http://bates.edu/~joishi"
baseurl = "http://bates.edu/"
canonifyurls = true
theme = "hugo-academic-group"
title = "Bates Astrophysical Fluid Dynamics Lab"
math = true
copyright = "&copy; Jeffrey S. Oishi, 2017; banner image NASA/SWRI/MSSS/Gerald Eichstädt/Seán Doran"

[taxonomies]
category = "categories"
tag = "tags"

[params]
  description = "Bates AFD Lab"
  author = "Jeffrey S. Oishi"
  email = "joishi@bates.edu"
  address = "Carnegie Science Room 141, Bates College, Lewiston, ME 04140"

  slogan = "Bates Astrophysical Fluid Dynamics Lab"
  #slogan_text = "Better Science through pretty pictures"

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 2
    detailed_list = true
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "#top"
      weight = 1

  [[menu.main]]
      name = "Research"
      url = "/research"
      weight = 2
      
  [[menu.main]]
      name = "Blog"
      url = "#posts"
      weight = 3

  [[menu.main]]
      name = "Publications"
      url = "#publications"
      weight = 4

  [[menu.main]]
      name = "Projects"
      url = "#projects"
      weight = 5

  [[menu.main]]
      name = "Members"
      url = "#members"
      weight = 6

  [[menu.main]]
      name = "Contact"
      url = "#contact"
      weight = 7
