layoutdir = "themes/hugo-academic-group/layouts"
publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://jsoishi.github.io/"
canonifyurls = true
theme = "hugo-academic-group"
title = "Bates Fluid Dynamics Group"
math = true
copyright = "&copy; Jeffrey S. Oishi, 2018; banner image NASA/SWRI/MSSS/Gerald Eichstädt/Seán Doran"

[taxonomies]
category = "categories"
tag = "tags"

[params]
  description = "Bates Fluids Group"
  author = "Jeffrey S. Oishi"
  email = "joishi@bates.edu"
  address = "Carnegie Science Room 141, Bates College, Lewiston, ME 04140"

  slogan = "Bates Fluid Dynamics Group"
  slogan_text = "Computing complicated fluid dynamics from turbulence to Stokes flow"

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "News"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 2
    detailed_list = true
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Joining the group"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "#top"
      weight = 1

  [[menu.main]]
      name = "Research"
      url = "/research"
      weight = 2
      identifier = "research"

  [[menu.main]]
      name = "Overview"
      url = "/research/overview"
      parent = "research"
      weight = 3        

  [[menu.main]]
      name = "Getting Started"
      url = "/research/getting_started"
      parent = "research"
      weight = 3

  [[menu.main]]
      name = "Dedalus Tutorials"
      url = "/research/dedalus_tutorials"
      parent = "research"
      weight = 4
      
  [[menu.main]]
      name = "News"
      url = "#posts"
      weight = 3

  [[menu.main]]
      name = "Publications"
      url = "#publications"
      parent = "research"
      weight = 4

  [[menu.main]]
      name = "Projects"
      url = "#projects"
      parent = "research"
      weight = 5

  [[menu.main]]
      name = "Members"
      url = "#members"
      weight = 6

  [[menu.main]]
      name = "Join Us!"
      url = "#vacancies"
      weight = 7

  [[menu.main]]
      name = "Contact"
      url = "#contact"
      weight = 8
